# Issue labels
- name: bug
  color: d73a4a
  description: Something isn't working

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: documentation
  color: 0075ca
  description: Improvements or additions to docs

- name: security
  color: ee0701
  description: Security related issues

- name: performance
  color: fbca04
  description: Performance related issues

- name: good first issue
  color: 7057ff
  description: Good for newcomers

- name: help wanted
  color: 008672
  description: We need help on this

- name: question
  color: ffb900
  description: Further information is requested

- name: wontfix
  color: ffffff
  description: This will not be worked on

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: invalid
  color: e4e669
  description: This doesn't seem right

- name: dependencies
  color: 0366d6
  description: Pull requests that update a dependency file
